default: &default
  adapter: redis_store
  # This is the Redis database used for caching.
  # It is recommended to use a separate Redis instance for caching in production.
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default

test:
  adapter: null_store

production:
  <<: *default