default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_DB_THREADS") { 5 } %>

development:
  <<: *default
  database: tripla_good_sleep_dev
  username: postgres
  password: postgres

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:postgres@localhost:5432/tripla_good_sleep_test" } %>
