default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_DB_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: tripla_good_sleep_dev
